#include "./scan_report.h"
#include "html.h"

// FIXME: Print them in order of smallest to largest port
// when individually passed in
//
// NOTE: There also very well may be a better/faster way of printing
// to both stdout and the FD stream so that i dont run 2 functions
// and just square the time needed to print everything

void handle_report(scan_info_t* s, const f32 cpu_time) {
  FILE* f = stdout;
  strcat(s->output_args.file_name, ".html");

  if (s->output_args.should_output == 1) {
    f = fopen(s->output_args.file_name, "w");
    if (!f) {
      shiba_fatal("Failed to write to file %s when outputting!", s->output_args.file_name);
    }

    if (s->output_args.html_file == 1) {
      print_html_report(s, f, cpu_time);
      f = stdout;
      print_report(s, f, cpu_time);
    }
    else if (s->output_args.greppable_file == 1) {
      print_greppable_report(s, f, cpu_time);
      f = stdout;
      print_report(s, f, cpu_time);
    }
    else if (s->output_args.smap_file == 1) {
      print_smap_file_report(s, f, cpu_time);
      f = stdout;
      print_report(s, f, cpu_time);
    }
  }
  else {
    print_report(s, f, cpu_time);
  }
}

void print_html_report(scan_info_t* s, FILE* f, const f32 cpu_time) {
  fflush(f);

  // boilerplate
  HTML_DOCTYPE;
  HTML_LANG("en");
  HTML_HEAD_OPEN;
  HTML_TITLE("Smap Scan Results");
  HTML_CHARSET;
  HTML_VIEWPORT;
  HTML_SMAP_STYLE;
  HTML_HEAD_CLOSE;
  // end of boilerplate

  HTML_HEAD_OPEN;
  HTML_H1_OPEN;
  fprintf(f, "Smap Scan Results");
  HTML_H1_CLOSE;

  HTML_PARAGRAPH_OPEN("scan");
  if (s->num_targets == 1) {
    fprintf(f, "Started smap scan on 1 target on %s", print_time());
  }
  else {
    fprintf(f, "Started smap scan on %d targets on %s", s->num_targets, print_time());
  }
  HTML_BR;
  HTML_PARAGRAPH_CLOSE;
  HTML_HEAD_CLOSE;

  HTML_BODY_OPEN;
  HTML_MAIN_OPEN;

  // we store the head for print_report
  target_t* head = s->targets;
  
  while (s->targets) {
    HTML_H3_OPEN;
    fprintf(f, "\n%s\n", s->targets->target);
    HTML_H3_CLOSE;

    HTML_PARAGRAPH_OPEN("host");
    fprintf(f, "Scanned: %d ports • Ignored: %d ports", s->num_ports_to_scan, s->targets->port_list->ignored_ports);
    HTML_PARAGRAPH_CLOSE;

    HTML_PARAGRAPH_OPEN("scan_info");
    HTML_STRONG_OPEN;
    fprintf(f, "Found %d open ports • %d closed ports", s->targets->port_list->open_ports, s->targets->port_list->closed_ports);
    HTML_STRONG_CLOSE;
    HTML_PARAGRAPH_CLOSE;

    HTML_H3_OPEN;
    fprintf(f, "Open Ports");
    HTML_H3_CLOSE;

    HTML_UL_OPEN("port_list");

    for (int i = 0; i < s->num_ports_to_scan; i++) {
      if (s->targets->port_list[s->port_nums[i]].state == PORT_OPEN) {
        HTML_LIST_OPEN;
        HTML_SPAN_OPEN("state open");
        fprintf(f, "%d\tOPEN", s->port_nums[i]);

        switch(s->scan_type) {
          case SCAN_TCP:
            fprintf(f, "/TCP\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_SYN:
            fprintf(f, "/SYN\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_UDP:
            fprintf(f, "/UDP\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_FIN:
            fprintf(f, "/FIN\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_PING:
            fprintf(f, "/PING\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;
        }
      }
    }
    HTML_UL_CLOSE;

    s->targets = s->targets->next;
  }

  HTML_H2_OPEN;
  (s->num_targets == 1) ?
  fprintf(f,"\n1 address scanned in %f seconds!\n", cpu_time) :
  fprintf(f,"\n%d addresses scanned in %f seconds!\n", s->num_targets, cpu_time);
  HTML_H2_CLOSE;

  HTML_MAIN_CLOSE;
  HTML_BODY_CLOSE;

  HTML_FOOTER_OPEN;
  HTML_PARAGRAPH_OPEN("end");
  fprintf(f, "Autogenerated by Smap");
  HTML_PARAGRAPH_CLOSE;
  HTML_FOOTER_CLOSE;

  HTML_CLOSE;

  // restore for print_report
  s->targets = head;
}

void print_report(scan_info_t* s, FILE* f, const f32 cpu_time) {
  fflush(f);

  while (s->targets) {
    fprintf(f, "\nsmap scan results for: %s\n", s->targets->target);
    fprintf(f, "Scanned: %d ports\t", s->num_ports_to_scan);
    fprintf(f, "Ignored: %d ports\t", s->targets->port_list->ignored_ports);
    fprintf(f, "Found %d open ports\t", s->targets->port_list->open_ports);
    fprintf(f, "%d closed ports\n", s->targets->port_list->closed_ports);
    fprintf(f, "PORT:\tSTATE:\n");
  
    for (int i = 0; i < s->num_ports_to_scan; i++) {
      if (s->targets->port_list[s->port_nums[i]].state == PORT_OPEN) {
        printf("%d\tOPEN", s->port_nums[i]);

        switch(s->scan_type) {
          case SCAN_TCP:
            printf("/TCP\n");
            break;

          case SCAN_SYN:
            printf("/SYN\n");
            break;

          case SCAN_UDP:
            printf("/UDP\n");
            break;

          case SCAN_FIN:
            printf("/FIN\n");
            break;

          case SCAN_PING:
            printf("/PING\n");
            break;

          default:
            printf("Reached default case of switch statement in (%s)", __FILE__);
            break;
        }
      }
    }

    s->targets = s->targets->next;
  }

  (s->num_targets == 1) ?
    printf("\n1 address scanned in %f seconds!\n", cpu_time) :
    printf("\n%d addresses scanned in %f seconds!\n", s->num_targets, cpu_time);
}

void print_greppable_report(scan_info_t* s, FILE* f, const f32 cpu_time) {
  // TODO:
}


void print_smap_file_report(scan_info_t* s, FILE* f, const f32 cpu_time) {
  // TODO:
}
