#include "./scan_report.h"
#include "html.h"

// FIXME: Print them in order of smallest to largest port
// when individually passed in
//

// TODO: I really should just write to file -> print to screen, this seems like
// too much overhead. "works for now" but will work on it soon.
// This whole file gives me some weird vibes. i wanna do it cleaner

void handle_report(scan_info_t* s, const f32 cpu_time) {
  FILE* stream = stdout;

  if (s->output_args.should_output == 1) {
    if (s->output_args.html_file == 1) {
      strcat(s->output_args.file_name, ".html");

      stream = fopen(s->output_args.file_name, "w");
      if (!stream) {
        shiba_fatal("Failed to write to file %s when outputting!", s->output_args.file_name);
      }

      print_html_report(s, stream, cpu_time);

      stream = stdout;
      print_report(s, stream, cpu_time);
    }
    else if (s->output_args.greppable_file == 1) {
      strcat(s->output_args.file_name, ".grep");

      stream = fopen(s->output_args.file_name, "w");
      if (!stream) {
        shiba_fatal("Failed to write to file %s when outputting!", s->output_args.file_name);
      }
      // TODO:
      print_greppable_report(s, stream, cpu_time);

      stream = stdout;
      print_report(s, stream, cpu_time);
    }
    else if (s->output_args.smap_file == 1) {
      strcat(s->output_args.file_name, ".smap");

      stream = fopen(s->output_args.file_name, "w");
      if (!stream) {
        shiba_fatal("Failed to write to file %s when outputting!", s->output_args.file_name);
      }

      print_smap_file_report(s, stream, cpu_time);

      stream = stdout;
      print_report(s, stream, cpu_time);
    }
  }
  else {
    print_report(s, stream, cpu_time);
  }
}

void print_html_report(scan_info_t* s, FILE* stream, const f32 cpu_time) {
  fflush(stream);

  // boilerplate
  HTML_DOCTYPE;
  HTML_LANG("en");
  HTML_HEAD_OPEN;
  HTML_TITLE("Smap Scan Results");
  HTML_CHARSET;
  HTML_VIEWPORT;
  HTML_SMAP_STYLE;
  HTML_HEAD_CLOSE;
  // end of boilerplate

  HTML_HEAD_OPEN;
  HTML_H1_OPEN;
  fprintf(stream, "Smap Scan Results");
  HTML_H1_CLOSE;

  HTML_PARAGRAPH_OPEN("scan");
  if (s->num_targets == 1) {
    fprintf(stream, "Started smap scan for 1 target on %s", print_time());
  }
  else {
    fprintf(stream, "Started smap scan for %d targets on %s", s->num_targets, print_time());
  }
  HTML_BR;
  HTML_PARAGRAPH_CLOSE;
  HTML_HEAD_CLOSE;

  HTML_BODY_OPEN;
  HTML_MAIN_OPEN;

  // we store the head for print_report
  target_t* head = s->targets;
  
  while (s->targets) {
    HTML_H3_OPEN;
    fprintf(stream, "\n%s\n", s->targets->target);
    HTML_H3_CLOSE;

    HTML_PARAGRAPH_OPEN("host");
    fprintf(stream, "Scanned: %d ports • Ignored: %d ports", s->num_ports_to_scan, s->targets->port_list->ignored_ports);
    HTML_PARAGRAPH_CLOSE;

    HTML_PARAGRAPH_OPEN("scan_info");
    HTML_STRONG_OPEN;
    fprintf(stream, "Found %d open ports • %d closed ports", s->targets->port_list->open_ports, s->targets->port_list->closed_ports);
    HTML_STRONG_CLOSE;
    HTML_PARAGRAPH_CLOSE;

    HTML_H3_OPEN;
    fprintf(stream, "Open Ports");
    HTML_H3_CLOSE;

    HTML_UL_OPEN("port_list");

    for (int i = 0; i < s->num_ports_to_scan; i++) {
      if (s->targets->port_list[s->port_nums[i]].state == PORT_OPEN) {
        HTML_LIST_OPEN;
        HTML_SPAN_OPEN("state open");
        fprintf(stream, "%d\tOPEN", s->port_nums[i]);

        switch(s->scan_type) {
          case SCAN_TCP:
            fprintf(stream, "/TCP\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_SYN:
            fprintf(stream, "/SYN\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_UDP:
            fprintf(stream, "/UDP\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_FIN:
            fprintf(stream, "/FIN\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_PING:
            fprintf(stream, "/PING\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;
        }
      }
    }
    HTML_UL_CLOSE;

    s->targets = s->targets->next;
  }

  HTML_H2_OPEN;
  (s->num_targets == 1) ?
  fprintf(stream,"\n1 address scanned in %f seconds!\n", cpu_time) :
  fprintf(stream,"\n%d addresses scanned in %f seconds!\n", s->num_targets, cpu_time);
  HTML_H2_CLOSE;

  HTML_MAIN_CLOSE;
  HTML_BODY_CLOSE;

  HTML_FOOTER_OPEN;
  HTML_PARAGRAPH_OPEN("end");
  fprintf(stream, "Autogenerated by Smap");
  HTML_PARAGRAPH_CLOSE;
  HTML_FOOTER_CLOSE;

  HTML_CLOSE;

  // restore for print_report
  s->targets = head;
}

void print_report(scan_info_t* s, FILE* stream, const f32 cpu_time) {
  fflush(stream);

  target_t* head = s->targets;

  while (s->targets) {
    fprintf(stream, "\nsmap scan results for: %s\n", s->targets->target);
    fprintf(stream, "Scanned: %d ports\t", s->num_ports_to_scan);
    fprintf(stream, "Ignored: %d ports\t", s->targets->port_list->ignored_ports);
    fprintf(stream, "Found %d open ports\t", s->targets->port_list->open_ports);
    fprintf(stream, "%d closed ports\n", s->targets->port_list->closed_ports);
    fprintf(stream, "PORT:\tSTATE:\n");
  
    for (int i = 0; i < s->num_ports_to_scan; i++) {
      if (s->targets->port_list[s->port_nums[i]].state == PORT_OPEN) {
        fprintf(stream, "%d\tOPEN", s->port_nums[i]);

        switch(s->scan_type) {
          case SCAN_TCP:
            fprintf(stream, "/TCP\n");
            break;

          case SCAN_SYN:
            fprintf(stream, "/SYN\n");
            break;

          case SCAN_UDP:
            fprintf(stream,"/UDP\n");
            break;

          case SCAN_FIN:
            fprintf(stream, "/FIN\n");
            break;

          case SCAN_PING:
            fprintf(stream, "/PING\n");
            break;
        }
      }
    }

    s->targets = s->targets->next;
  }

  (s->num_targets == 1) ?
    fprintf(stream, "\n1 address scanned in %f seconds!\n", cpu_time) :
    fprintf(stream, "\n%d addresses scanned in %f seconds!\n", s->num_targets, cpu_time);

  s->targets = head;
}

void print_greppable_report(scan_info_t* s, FILE* stream, const f32 cpu_time) {
  // TODO:
}


void print_smap_file_report(scan_info_t* s, FILE* stream, const f32 cpu_time) {
  print_report(s, stream, cpu_time);
}
