#include "./scan_report.h"
#include "html.h"

void handle_report(scan_info_t* s, const f32 cpu_time) {
  FILE* stream = stdout;

  if (s->output_args.should_output == TRUE) {
    strcat(s->output_args.file_name, s->output_args.file_format);

    stream = fopen(s->output_args.file_name, "w");
    if (!stream) { // TODO: clarify what went wrong (out of space etc)
      shiba_fatal("Failed to write to file %s when outputting!", s->output_args.file_name);
    }

    if (strcmp(s->output_args.file_format, HTML_FILE_FORMAT) == 0) {
      print_html_report(s, stream, cpu_time);
    }
    else if (strcmp(s->output_args.file_format, SMAP_FILE_FORMAT) == 0) {
      print_smap_file_report(s, stream, cpu_time);
    }
    else if (strcmp(s->output_args.file_format, GREP_FILE_FORMAT) == 0) {
      print_greppable_report(s, stream, cpu_time);
    }
    // -oA
    else {
      // TODO: Add some -oA functionality
    }
    
    fclose(stream);
    stream = stdout;
    print_report(s, stream, cpu_time);
  }
  else {
    print_report(s, stream, cpu_time);
  }
}

void print_html_report(scan_info_t* s, FILE* stream, const f32 cpu_time) {
  fflush(stream);

  // boilerplate
  HTML_DOCTYPE;
  HTML_LANG("en");
  HTML_HEAD_OPEN;
  HTML_TITLE("Smap Scan Results");
  HTML_CHARSET;
  HTML_VIEWPORT;
  HTML_SMAP_STYLE;
  HTML_HEAD_CLOSE;
  // end of boilerplate

  HTML_HEAD_OPEN;
  HTML_H1_OPEN;
    fprintf(stream, "Smap Scan Results");
  HTML_H1_CLOSE;

  HTML_PARAGRAPH_OPEN("scan");
    if (s->num_targets == 1) {
      fprintf(stream, "Smap scan for 1 target started at %s", print_time());
    }
    else {
      fprintf(stream, "Smap scan for %d targets started at %s", s->num_targets, print_time());
    }
  HTML_BR;
  HTML_PARAGRAPH_CLOSE;
  HTML_HEAD_CLOSE;

  HTML_BODY_OPEN;
  HTML_MAIN_OPEN;

  // we store the head for print_report
  target_t* head = s->targets;
  
  while (s->targets) {
    HTML_H3_OPEN;
      fprintf(stream, "\n%s\n", s->targets->target);
    HTML_H3_CLOSE;

    HTML_PARAGRAPH_OPEN("host");
      fprintf(stream, "Scanned: %d ports • Ignored: %d ports", s->num_ports_to_scan, s->targets->ignored_ports);
    HTML_PARAGRAPH_CLOSE;

    HTML_PARAGRAPH_OPEN("scan_info");
    HTML_STRONG_OPEN;
      fprintf(stream, "Found %d open ports • Not shown: %d closed ports", s->targets->open_ports, s->targets->closed_ports);
    HTML_STRONG_CLOSE;
    HTML_PARAGRAPH_CLOSE;

    HTML_H3_OPEN;
      fprintf(stream, "Open Ports");
    HTML_H3_CLOSE;

    HTML_UL_OPEN("port_list");

    for (int i = 0; i < s->num_ports_to_scan; i++) {
      if (s->targets->port_list[s->port_nums[i]].state == PORT_OPEN) {
        HTML_LIST_OPEN;
        HTML_SPAN_OPEN("state open");
        fprintf(stream, "%d\tOPEN", s->port_nums[i]);

        switch(s->scan_type) {
          case SCAN_TCP:
            fprintf(stream, "/TCP\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_SYN:
            fprintf(stream, "/SYN\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_UDP:
            fprintf(stream, "/UDP\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_FIN:
            fprintf(stream, "/FIN\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;

          case SCAN_PING:
            fprintf(stream, "/PING\n");
            HTML_LIST_CLOSE;
            HTML_SPAN_CLOSE;
            break;
        }
      }
    }
    HTML_UL_CLOSE;

    s->targets = s->targets->next;
  }

  HTML_H3_OPEN;
    (s->num_targets == 1) ?
    fprintf(stream,"\n1 address scanned in %f seconds!\n", cpu_time) :
    fprintf(stream,"\n%d addresses scanned in %f seconds!\n", s->num_targets, cpu_time);
  HTML_H3_CLOSE;

  HTML_MAIN_CLOSE;
  HTML_BODY_CLOSE;

  HTML_FOOTER_OPEN;
  HTML_PARAGRAPH_OPEN("end");
    fprintf(stream, "Autogenerated by Smap");
  HTML_PARAGRAPH_CLOSE;
  HTML_FOOTER_CLOSE;

  HTML_CLOSE;

  // restore for print_report
  s->targets = head;
}

void print_report(scan_info_t* s, FILE* stream, const f32 cpu_time) {
  fflush(stream);

  target_t* head = s->targets;

  while (s->targets) {
    fprintf(stream, "\nsmap scan results for: %s\n", s->targets->target);
    fprintf(stream, "Scanned: %d port(s)\t", s->num_ports_to_scan);
    fprintf(stream, "Ignored: %d ports\t", s->targets->ignored_ports);
    fprintf(stream, "Found %d open port(s)\n", s->targets->open_ports);
    fprintf(stream, "Not shown: %d closed ports\n\n", s->targets->closed_ports);
    fprintf(stream, "PORT:\tSTATE:\n");
  
    for (int i = 0; i < s->num_ports_to_scan; i++) {
      if (s->targets->port_list[s->port_nums[i]].state == PORT_OPEN) {
        fprintf(stream, "%d\tOPEN", s->port_nums[i]);

        switch(s->scan_type) {
          case SCAN_TCP:
            fprintf(stream, "/TCP\n");
            break;

          case SCAN_SYN:
            fprintf(stream, "/SYN\n");
            break;

          case SCAN_UDP:
            fprintf(stream,"/UDP\n");
            break;

          case SCAN_FIN:
            fprintf(stream, "/FIN\n");
            break;

          case SCAN_PING:
            fprintf(stream, "/PING\n");
            break;
        }
      }
    }

    s->targets = s->targets->next;
  }

  (s->num_targets == 1) ?
    fprintf(stream, "\n1 address scanned in %f seconds!\n", cpu_time) :
    fprintf(stream, "\n%d addresses scanned in %f seconds!\n", s->num_targets, cpu_time);

  s->targets = head;
}

void print_greppable_report(scan_info_t* s, FILE* stream, const f32 cpu_time) {
  fflush(stream);
  fprintf(stream, "# smap scan started at: %s", print_time());

  target_t* head = s->targets;

  while (s->targets) {
    fprintf(stream, "Host: %s\t", s->targets->target);
    fprintf(stream, "Ports: ");

    for (int i = 0; i < s->num_ports_to_scan; i++) {
      if (s->targets->port_list[s->port_nums[i]].state == PORT_OPEN) {
        fprintf(stream, "%d/OPEN", s->port_nums[i]);
        
        switch(s->scan_type) {
          case SCAN_TCP:
            fprintf(stream, "/TCP, ");
            break;

          case SCAN_SYN:
            fprintf(stream, "/SYN, ");
            break;

          case SCAN_UDP:
            fprintf(stream,"/UDP, ");
            break;

          case SCAN_FIN:
            fprintf(stream, "/FIN, ");
            break;

          case SCAN_PING:
            fprintf(stream, "/PING, ");
            break;
        }
      }
    }

    fprintf(stream, " Scanned: %d ports, ", s->num_ports_to_scan);
    fprintf(stream, " Ignored: %d ports\n", s->targets->ignored_ports);
    s->targets = s->targets->next;
  }

  (s->num_targets == 1) ?
    fprintf(stream, "# 1 address scanned in %f seconds!\n", cpu_time) :
    fprintf(stream, "# %d addresses scanned in %f seconds!\n", s->num_targets, cpu_time);

  s->targets = head;
}


void print_smap_file_report(scan_info_t* s, FILE* stream, const f32 cpu_time) {
  print_report(s, stream, cpu_time);
}

void print_css_file() {
  FILE* f = fopen("smap_style.css", "w");
  if (!f) { // TODO: be more specific
    fprintf(stderr, "Failed to create smap_style.css file!\n");
    return;
  }

  // prepare for an entire CSS file!
  fputs(
        "/* This was taken from Mike Mai at https://mikemai.net/. I added\n"
        " * some minor adjustments so it'd fit my needs, but its basically his!\n"
        " */\n"
        "@layer config, resets, custom;\n\n"
        "@layer custom {\n"
        ":root {\n"
        "  position: relative;\n"
        "  min-block-size: 100svb;\n"
        "  &::before,\n"
        "  &::after {\n"
        "    content: \"\";\n"
        "    inset: 0;\n"
        "    pointer-events: none;\n"
        "  }\n\n",
        f);

  fputs(
      "  @media (prefers-reduced-motion: no-preference) {\n"
      "    &::before {\n"
      "      position: absolute;\n"
      "      z-index: -1;\n"
      "      background: radial-gradient(\n"
      "          circle at 20% 30%,\n"
      "          oklch(90% 0.08 280 / 0.35),\n"
      "          transparent 40%\n"
      "        ),\n"
      "        radial-gradient(\n"
      "          circle at 80% 40%,\n"
      "          oklch(88% 0.10 320 / 0.38),\n"
      "          transparent 40%\n"
      "        ),\n"
      "        radial-gradient(\n"
      "          circle at 50% 70%,\n"
      "          oklch(92% 0.07 200 / 0.32),\n"
      "          transparent 50%\n"
      "        ),\n"
      "        radial-gradient(\n"
      "          circle at 30% 80%,\n"
      "          oklch(94% 0.06 290 / 0.30),\n"
      "          transparent 50%\n"
      "        ),\n"
      "        radial-gradient(\n"
      "          circle at 60% 20%,\n"
      "          oklch(89% 0.09 260 / 0.40),\n"
      "          transparent 60%\n"
      "        ),\n"
      "        canvas;\n"
      "      background-size: 300% 300%;\n"
      "      will-change: background-position;\n"
      "      -webkit-animation: gradient 35s ease-in-out infinite;\n"
      "      animation: gradient 35s ease-in-out infinite;\n"
      "    }\n"
      "  }\n\n",
      f);

  fputs(
      "  @media (forced-colors: none) {\n"
      "    &::after {\n"
      "      position: fixed;\n"
      "      opacity: 0.28;\n"
      "    }\n"
      "  }\n"
      "}\n\n",
      f);

  fputs(
      ":root {\n"
      "  --color-hero-fg: white;\n"
      "  --color-hero-bg: black;\n"
      "  @media (prefers-color-scheme: light) {\n"
      "    --color-hero-fg: black;\n"
      "    --color-hero-bg: white;\n"
      "  }\n"
      "  &:has(input[name=\"color-scheme\"][value*=\"light\"]:checked) {\n"
      "    --color-hero-fg: black;\n"
      "    --color-hero-bg: white;\n"
      "    color-scheme: light;\n"
      "  }\n"
      "  &:has(input[name=\"color-scheme\"][value*=\"dark\"]:checked) {\n"
      "    --color-hero-fg: white;\n"
      "    --color-hero-bg: black;\n"
      "    color-scheme: dark;\n"
      "  }\n"
      "  &:has(input[name=\"color-scheme\"][value=\"system\"]:checked) {\n"
      "    color-scheme: dark light;\n"
      "  }\n"
      "  &:has(input[name=\"color-scheme\"][value*=\"plain\"]:checked) {\n"
      "    &::before {\n"
      "      background: canvas;\n"
      "    }\n"
      "    h1 {\n"
      "      color: canvastext;\n"
      "    }\n"
      "  }\n"
      "}\n\n",
      f);

  fputs(
      "body {\n"
      "  margin: 0;\n"
      "  min-height: 100vh;\n"
      "  display: flex;\n"
      "  flex-direction: column;\n"
      "}\n\n"
      "*:focus-visible {\n"
      "  outline: 2px solid;\n"
      "  outline-offset: 2px;\n"
      "}\n\n"
      ":where(footer) {\n"
      "  padding-block: 0.5rem 0.5rem;\n"
      "  background-color: color-mix(in oklch, canvastext, transparent 96%);\n"
      "}\n\n"
      ":where(main, footer) {\n"
      "  padding-inline: var(--page-padding-inline);\n"
      "}\n\n",
      f);

  fputs(
      "h1 {\n"
      "  display: grid;\n"
      "  text-align: center;\n"
      "  gap: 0.1ex;\n"
      "  margin: 0 auto;\n"
      "  font-size: clamp(1rem, 4vw, 2rem);\n"
      "  line-height: 1.4;\n"
      "  color: CanvasText;\n"
      "  @media (prefers-reduced-motion: no-preference) and (forced-colors: none) {\n"
      "    color: transparent;\n"
      "    text-shadow: 0 0 0.1ex color-mix(in oklch, CanvasText, transparent 70%);\n"
      "    background: linear-gradient(\n"
      "      120deg,\n"
      "      CanvasText,\n"
      "      color-mix(in oklch, CanvasText 80%, linktext 20%),\n"
      "      linktext,\n"
      "      CanvasText,\n"
      "      color-mix(in oklch, CanvasText 80%, linktext 20%),\n"
      "      CanvasText,\n"
      "      color-mix(in oklch, CanvasText 90%, Canvas 10%)\n"
      "    );\n"
      "    background-size: 600% 600%;\n"
      "    -webkit-background-clip: text;\n"
      "    background-clip: text;\n"
      "    will-change: background-position;\n"
      "    -webkit-animation: shine 17.5s cubic-bezier(0.78, 0.11, 0, 0.91) infinite;\n"
      "    animation: shine 17.5s cubic-bezier(0.78, 0.11, 0, 0.91) infinite;\n"
      "  }\n"
      "}\n\n",
      f);

  fputs(
      "p.scan {\n"
      "  display: block;\n"
      "  -webkit-margin-after: 1cap;\n"
      "  margin-block-end: 1cap;\n"
      "  font-family: var(--font);\n"
      "  font-size: var(--pt-english);\n"
      "  font-style: italic;\n"
      "  text-transform: capitalize;\n"
      "  text-indent: 0.1ch;\n"
      "  text-align: center;\n"
      "  line-height: 1;\n"
      "}\n\n"
      ":where(main) {\n"
      "  padding-block: 2rem;\n"
      "  overflow-x: clip;\n"
      "  flex: 1;\n"
      "}\n\n",
      f);

  fputs(
      ":where(h1, h2, h3, h4, h5, h6) {\n"
      "  margin-block: 1.5ex 0.5ex;\n"
      "  font-family: var(--font-heading);\n"
      "  font-weight: inherit;\n"
      "  font-variant: small-caps;\n"
      "  text-transform: uppercase;\n"
      "  -webkit-hyphens: auto;\n"
      "  -ms-hyphens: auto;\n"
      "  hyphens: auto;\n"
      "  word-break: break-word;\n"
      "}\n\n"
      "main > * + * {\n"
      "  margin-top: 1rem;\n"
      "}\n\n"
      ":where(ol, ul) {\n"
      "  -webkit-margin-before: 1rem;\n"
      "  margin-block-start: 1rem;\n"
      "}\n\n",
      f);

  fputs(
      ":where(ul.port_list) {\n"
      "  --_padding: calc(var(--border-size) * 2);\n"
      "  padding-block: var(--_padding);\n"
      "  padding-inline: 2.5ex var(--_padding);\n"
      "  font-size: 4ex;\n"
      "  line-height: 1;\n"
      "  background-color: var(--border-color);\n"
      "  border: 1px solid transparent;\n"
      "  border-radius: var(--border-radius);\n"
      "  li {\n"
      "    background-color: color-mix(in oklch, canvastext, transparent 95%);\n"
      "    border-radius: calc(var(--border-radius) - var(--_padding) / 2);\n"
      "  }\n"
      "  li + li {\n"
      "    -webkit-margin-before: 4px;\n"
      "    margin-block-start: 4px;\n"
      "  }\n"
      "  li :is(span) {\n"
      "    display: inline-block;\n"
      "    vertical-align: middle;\n"
      "    padding-block: 0.85ex 1ex;\n"
      "    padding-inline: 2ex;\n"
      "    font-size: 1rem;\n"
      "    line-height: 1.4;\n"
      "  }\n"
      "}\n\n",
      f);

  fputs(
      "span.state.open {\n"
      "  color: linktext;\n"
      "}\n\n"
      "p.host,\n"
      "p.scan_info,\n"
      "p.end {\n"
      "  font-family: var(--font);\n"
      "  line-height: var(--leading);\n"
      "}\n\n"
      "p.scan_info strong {\n"
      "  font-weight: var(--font-weight-bold);\n"
      "}\n\n",
      f);

  fputs(
      ".visually-hidden:not(:focus):not(:active) {\n"
      "  -webkit-clip-path: inset(50%);\n"
      "  clip-path: inset(50%);\n"
      "  height: 1px;\n"
      "  overflow: hidden;\n"
      "  position: absolute;\n"
      "  white-space: nowrap;\n"
      "  width: 1px;\n"
      "}\n"
      "}\n\n",
      f);

  fputs(
      "@layer config {\n"
      ":root {\n"
      "  --gutter: clamp(2ch, 5vmin, 5ch);\n"
      "  --stack: clamp(1cap, 5vmax, 3cap);\n"
      "  --line-length: 75ch;\n"
      "  --section-spacing: 2rem;\n"
      "  --page-max-inline-size: min(var(--line-length), 80dvi);\n"
      "  --page-padding-inline: calc((100dvi - var(--page-max-inline-size)) / 2);\n"
      "  --hero-max-inline-size: 80dvi;\n"
      "  --hero-padding-inline: calc((100dvi - var(--hero-max-inline-size)) / 2);\n"
      "  --font: \"IM Fell English\", \"Georgia\", serif;\n"
      "  --font-heading: \"Boldonse\", system-ui, sans-serif;\n"
      "  --font-weight: 400;\n"
      "  --font-weight-semibold: 600;\n"
      "  --font-weight-bold: 900;\n"
      "  --font-size-min: 125%;\n"
      "  --font-size-max: 175%;\n"
      "  --font-size-small-ratio: 0.8;\n"
      "  --leading: 1.4;\n"
      "  --paragraph-indent: 1.5cap;\n"
      "  --pt-double-canon: 4.666rem;\n"
      "  --pt-canon: 3.999rem;\n"
      "  --pt-double-great-primer: 2.999rem;\n"
      "  --pt-double-english: 2.333rem;\n"
      "  --pt-double-pica: 2rem;\n"
      "  --pt-paragon: 1.666rem;\n"
      "  --pt-great-primer: 1.5rem;\n"
      "  --pt-english: 1.166rem;\n"
      "  --pt-pica: 1rem;\n"
      "  --pt-small-pica: 0.916rem;\n"
      "  --pt-long-primer: 0.833rem;\n"
      "  --pt-bourgeois: 0.75rem;\n"
      "  --pt-minion: 0.583rem;\n"
      "  --border-radius: 1ex;\n"
      "  --border-size: 4px;\n"
      "  @media (forced-colors: active) {\n"
      "    --border-size: 1px;\n"
      "  }\n"
      "  --border-color: color-mix(in oklch, canvastext, transparent 95%);\n"
      "  font-family: var(--font);\n"
      "  font-size: clamp(\n"
      "    var(--font-size-min),\n"
      "    var(--font-size-min) * 0.9 + 0.5dvi,\n"
      "    var(--font-size-max)\n"
      "  );\n"
      "  font-weight: var(--font-weight);\n"
      "  line-height: var(--leading);\n"
      "}\n\n",
      f);

  fputs(
      "@-webkit-keyframes gradient {\n"
      "  0%,\n"
      "  100% {\n"
      "    background-position: 15% 85%;\n"
      "    filter: hue-rotate(0deg);\n"
      "  }\n"
      "  10% {\n"
      "    background-position: 85% 15%;\n"
      "  }\n"
      "  20% {\n"
      "    filter: hue-rotate(15deg);\n"
      "    background-position: 45% 60%;\n"
      "  }\n"
      "  30% {\n"
      "    background-position: 10% 20%;\n"
      "  }\n"
      "  40% {\n"
      "    background-position: 70% 90%;\n"
      "  }\n"
      "  50% {\n"
      "    background-position: 30% 30%;\n"
      "    filter: hue-rotate(30deg);\n"
      "  }\n"
      "  60% {\n"
      "    background-position: 90% 40%;\n"
      "  }\n"
      "  70% {\n"
      "    background-position: 40% 90%;\n"
      "  }\n"
      "  80% {\n"
      "    background-position: 20% 10%;\n"
      "    filter: hue-rotate(-15deg);\n"
      "  }\n"
      "  90% {\n"
      "    background-position: 60% 70%;\n"
      "  }\n"
      "}\n\n",
      f);

  fputs(
      "@keyframes gradient {\n"
      "  0%,\n"
      "  100% {\n"
      "    background-position: 15% 85%;\n"
      "    filter: hue-rotate(0deg);\n"
      "  }\n"
      "  10% {\n"
      "    background-position: 85% 15%;\n"
      "  }\n"
      "  20% {\n"
      "    filter: hue-rotate(15deg);\n"
      "    background-position: 45% 60%;\n"
      "  }\n"
      "  30% {\n"
      "    background-position: 10% 20%;\n"
      "  }\n"
      "  40% {\n"
      "    background-position: 70% 90%;\n"
      "  }\n"
      "  50% {\n"
      "    background-position: 30% 30%;\n"
      "    filter: hue-rotate(30deg);\n"
      "  }\n"
      "  60% {\n"
      "    background-position: 90% 40%;\n"
      "  }\n"
      "  70% {\n"
      "    background-position: 40% 90%;\n"
      "  }\n"
      "  80% {\n"
      "    background-position: 20% 10%;\n"
      "    filter: hue-rotate(-15deg);\n"
      "  }\n"
      "  90% {\n"
      "    background-position: 60% 70%;\n"
      "  }\n"
      "}\n\n",
      f);

  fputs(
      "@-webkit-keyframes shine {\n"
      "  0%,\n"
      "  100% {\n"
      "    background-position: 0% 50%;\n"
      "    filter: hue-rotate(0deg);\n"
      "  }\n"
      "  50% {\n"
      "    background-position: 100% 50%;\n"
      "    filter: hue-rotate(60deg);\n"
      "  }\n"
      "}\n\n"
      "@keyframes shine {\n"
      "  0%,\n"
      "  100% {\n"
      "    background-position: 0% 50%;\n"
      "    filter: hue-rotate(0deg);\n"
      "  }\n"
      "  50% {\n"
      "    background-position: 100% 50%;\n"
      "    filter: hue-rotate(60deg);\n"
      "  }\n"
      "}\n"
      "}\n\n",
      f);

  fputs(
      "@layer resets {\n"
      "  *,\n"
      "  ::before,\n"
      "  ::after {\n"
      "    font-feature-settings: \"kern\";\n"
      "    -webkit-font-kerning: normal;\n"
      "    font-kerning: normal;\n"
      "    text-wrap: pretty;\n"
      "    box-sizing: border-box;\n"
      "    @media (prefers-color-scheme: dark) {\n"
      "      -moz-osx-font-smoothing: grayscale !important;\n"
      "      -webkit-font-smoothing: antialiased !important;\n"
      "    }\n"
      "  }\n\n"
      "  input,\n"
      "  select,\n"
      "  textarea,\n"
      "  button {\n"
      "    font: inherit;\n"
      "  }\n\n"
      "  svg {\n"
      "    fill: currentcolor;\n"
      "  }\n\n"
      "  @media (prefers-reduced-motion: no-preference) {\n"
      "    :root {\n"
      "      scroll-behavior: smooth;\n"
      "    }\n"
      "  }\n"
      "}\n",
      f);

  fclose(f);
}
